---
- name: Add Microsoft apt keys
  become: true
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft repository
  become: true
  when: ansible_os_family == "Debian"
  get_url:
    url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/prod.list"
    dest: /etc/apt/sources.list.d/microsoft.list
    force: yes

- name: Update cache and install PowerShell
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: powershell

- name: Clone Invoke-Obfuscation
  become: true
  when: ansible_os_family == "Debian"
  git:
    repo: https://github.com/danielbohannon/Invoke-Obfuscation.git
    dest: "{{ io_git_location }}/Invoke-Obfuscation"
    update: yes